### ISSUE TITLE
Please update pyside2 dependency to pyside6 to be able to use python > 3.7

### ISSUE THREAD

**Issue by stefaneidelloth** [pedroCabrera/PyFlow#115]
I installed PyFlow using

`pip install git+https://github.com/wonderworks-software/PyFlow.git@master`

on python 3.11

When I try to start PyFlow I get

`ModuleNotFoundError: No module named 'PySide2'`

When trying to install PySide2 with

`pip install PySide2` 

I get

```
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2

```
Following https://stackoverflow.com/questions/75707701/why-i-can-not-install-pyside2

I installed pyside6 using

`pip install pyside6`

However, PyFlow still asks for PySide2

**Comment by pedroCabrera** [comment]
New pyside6 branch developed, will merge to master soon

**Comment by Flippo24** [comment]
@pedroCabrera Have you thought about switching from Qt.py to QtPy or to do without Qt.py and use PySide6 directly? 
PySide6 is not fully supported by qt.py from what I read.

**Comment by pedroCabrera** [comment]
Hi, yes there is a pyside6 branch under development, it's working already, just fixing minor things

**Comment by Flippo24** [comment]
Yes, I have just tried your branch. But I get this error message when I start it. 

> (venv) [flippo@Booker PyFlow-pyside6]$ python pyflow.py
Traceback (most recent call last):
  File "/home/flippo/Projekte/PyFlow-pyside6/pyflow.py", line 17, in <module>
    from PyFlow.App import PyFlow
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/App.py", line 42, in <module>
    from PyFlow.Packages.PyFlowBase.Tools.PropertiesTool import PropertiesTool
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/Packages/PyFlowBase/__init__.py", line 92, in <module>
    from PyFlow.Packages.PyFlowBase.Tools.LoggerTool import LoggerTool
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/Packages/PyFlowBase/Tools/LoggerTool.py", line 29, in <module>
    REDIRECT = ConfigManager().shouldRedirectOutput()
               ^^^^^^^^^^^^^^^
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/Core/Common.py", line 734, in __call__
    self.instance = self.cls(*args, **kwds)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/ConfigManager.py", line 45, in __init__
    data = InputManager().serialize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/Input.py", line 192, in serialize
    result[actionName].append(actionVariant.toJson())
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flippo/Projekte/PyFlow-pyside6/PyFlow/Input.py", line 132, in toJson
    "mouse": int(self.__data["mouse"]),
             ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'MouseButton'


I have installed the requirements-standalone.

> (venv) [flippo@Booker PyFlow-pyside6]$ pip install -r requirements/requirements-standalone.txt
Collecting PySide6
  Using cached PySide6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (77 kB)
Collecting qtpy
  Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)
Collecting blinker
  Using cached blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting docutils
  Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Collecting SQLAlchemy
  Using cached SQLAlchemy-2.0.25-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting shiboken6==6.6.1
  Using cached shiboken6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (245 kB)
Collecting PySide6-Essentials==6.6.1
  Using cached PySide6_Essentials-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (82.3 MB)
Collecting PySide6-Addons==6.6.1
  Using cached PySide6_Addons-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (125.2 MB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting typing-extensions>=4.6.0
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting greenlet!=0.4.17
  Using cached greenlet-3.0.3-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (620 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.0-py3-none-any.whl (120 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Installing collected packages: urllib3, typing-extensions, shiboken6, packaging, idna, greenlet, docutils, charset-normalizer, certifi, blinker, SQLAlchemy, requests, qtpy, PySide6-Essentials, PySide6-Addons, PySide6
Successfully installed PySide6-6.6.1 PySide6-Addons-6.6.1 PySide6-Essentials-6.6.1 SQLAlchemy-2.0.25 blinker-1.7.0 certifi-2024.2.2 charset-normalizer-3.3.2 docutils-0.20.1 greenlet-3.0.3 idna-3.6 packaging-23.2 qtpy-2.4.1 requests-2.31.0 shiboken6-6.6.1 typing-extensions-4.9.0 urllib3-2.2.0

What have I done wrong?

**Comment by pedroCabrera** [comment]
Mm weird, I have it working in a fresh install, can you try to delete your preferences? Maybe Is some old preferences

**Comment by Flippo24** [comment]
I have used a new virtual environment with Python 3.11.

**Comment by pedroCabrera** [comment]
But do you have any pyflow settings from previous versions?

**Comment by Flippo24** [comment]
Not that I know of. Where are they located?

**Comment by Flippo24** [comment]
Have you tried if it works without your Configs directory? When creating the input.json, I get the error mentioned above. 
Can you please attach inputs.json so that I can see how the elements are written correctly.

**Comment by pedroCabrera** [comment]
What if you delete the config folder so it's created fresh? , it should run. 
But yeah there is a problem with the key mapping with pyside6 port, I'll try to fix these days, but it would start and work anyway

**Comment by Flippo24** [comment]
The problem is creating the files in the folder. I don't have a folder and the error occurs when creating the inputs.json.

**Comment by pedroCabrera** [comment]
Ok interesting, will debug it and let you know! Thanks!

**Comment by Flippo24** [comment]
Can you still send me an inputs.json, or at least an excerpt of what the modifiers look like?

**Comment by Flippo24** [comment]
I had to change it to make it work.

   ```
def toJson(self):
        saveData = {"name": self._name,
                    "group": self._group,
                    "mouse": int(self.__data["mouse"].value),
                    "actionType": self.actionType.value}
        key = self.__data["key"]
        saveData["key"] = int(key) if key is not None else None

        modifiersList = self._modifiersToList(self.__data["modifiers"])

        saveData["modifiers"] = [i.value for i in modifiersList]
        return saveData
```

**Comment by Flippo24** [comment]
Works really well. Thanks for your work. If I find anything else, I'll let you know.

**Comment by pedroCabrera** [comment]
Thanks for the fix!! I pushed the chage to the branch!
Still need to fix in the settings windows that for some reason some chinese symbols appears since the change to pyside6

**Comment by Flippo24** [comment]
I've also seen that with the chinese characters. I think it is due to the value of the modifier which is not in the same format as when reading in.

Have a look at these two lines. 

https://github.com/wonderworks-software/PyFlow/blob/dcec2c50845e41d3061d481fc23e586cd88d46b4/PyFlow/Input.py#L132

https://github.com/wonderworks-software/PyFlow/blob/dcec2c50845e41d3061d481fc23e586cd88d46b4/PyFlow/UI/Widgets/KeyboardModifiersCapture.py#L46

**Comment by pedroCabrera** [comment]
Its fixed now also! Thanks for the help with this!

**Comment by Flippo24** [comment]
The requirements in setup.py are also outdated and still need to be adapted.

**Comment by Flippo24** [comment]
It didn't quite work that way with the characters.
![grafik](https://github.com/wonderworks-software/PyFlow/assets/5230426/536a8909-f2f1-46c4-9646-53ceec9dc416)

**Comment by pedroCabrera** [comment]
What do you mean?

**Comment by pedroCabrera** [comment]
> The requirements in setup.py are also outdated and still need to be adapted.

Updated!

**Comment by Flippo24** [comment]
> It didn't quite work that way with the characters. ![grafik](https://private-user-images.githubusercontent.com/5230426/303091233-536a8909-f2f1-46c4-9646-53ceec9dc416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODcyODksIm5iZiI6MTcwNzM4Njk4OSwicGF0aCI6Ii81MjMwNDI2LzMwMzA5MTIzMy01MzZhODkwOS1mMmYxLTQ2YzQtOTY0Ni01M2NlZWM5ZGM0MTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTAwOTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODUwYWQwZWZjN2Y2Nzc0MTMwYzQyYjhhOTA4MDI2MWY5Mjk1ZmY4OGE5MjM2Y2FhOTgyYjA3ZTFhOWE2OGJlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LXNyj3-5eglRyEu7-6NE6tiJmP9z6iBrU0ROZsAqtq4)

Cutting off the last two characters was not the solution. Entering a new combination only works here if the character is visible. The Chinese is only displayed because there is no key. 
If I insert a print(QtGui.QKeySequence(modifiers)) here, I see that all keys are unknown.
https://github.com/wonderworks-software/PyFlow/blob/dcec2c50845e41d3061d481fc23e586cd88d46b4/PyFlow/UI/Widgets/KeyboardModifiersCapture.py#L46

result:
`QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(AltModifier), Qt::Key_unknown) at 0x7f5ccd8eb4c0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc6ec540>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc6ed280>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc6eddc0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ShiftModifier|ControlModifier), Qt::Key_unknown) at 0x7f5ccc6ef180>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ShiftModifier|ControlModifier), Qt::Key_unknown) at 0x7f5ccd6ad940>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ShiftModifier|ControlModifier), Qt::Key_unknown) at 0x7f5ccc700840>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ShiftModifier|ControlModifier), Qt::Key_unknown) at 0x7f5ccc7013c0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc702140>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc702c00>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc703cc0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc7246c0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(AltModifier), Qt::Key_unknown) at 0x7f5ccc724cc0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(AltModifier), Qt::Key_unknown) at 0x7f5ccc725800>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc7278c0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc727c00>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(AltModifier), Qt::Key_unknown) at 0x7f5ccc744980>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc745680>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc746000>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ShiftModifier|ControlModifier), Qt::Key_unknown) at 0x7f5ccc7467c0>,)
QKeySequence(<PySide6.QtCore.QKeyCombination(QFlags<Qt::KeyboardModifier>(ControlModifier), Qt::Key_unknown) at 0x7f5ccc747040>,)`

It looks like there is still something wrong with the serialization.
I always delete the config directory before testing.

**Comment by Flippo24** [comment]
Sorry, I misunderstood everything.
I thought you could enter the complete combination in the left column, e.g. Ctrl+D. But now it i got it and I have understood how it works. The modifiers are on the left and the keys on the right. This is also the reason why the key is unknown. So your change was correct after all. So all's well and I've learned something again.

**Comment by pedroCabrera** [comment]
Haha no prob, btw , are you on the discord server? Would be nice to talk to you as you are helping to debug everything, will be nice to have you there!
