### ISSUE TITLE
JSON not serializable on output (so saved file is corrupted)

### ISSUE THREAD

**Issue by simoneluce** [pedroCabrera/PyFlow#126]
![JSON not serializable](https://github.com/wonderworks-software/PyFlow/assets/153103493/3b713dae-0856-4744-bf24-8d2ddb434a9b)

I am currently using pyflow to integrate an engineering Framework from Ansys (DPF core).
I need to pass an object instance from the central node to the right one.
To do so I encapsulated the ouput data into a list and the last node unpacks the list and plot the results. 
(in the picture a simplified example)
**It works as expected**, but the file cannot be saved properly since the massed element (a class instance) is **not JSON serializable**.
(The  output file is generated, but it is 0kb)

There should be a way to just _not save_ the ouput values of the nodes.

**Comment by pedroCabrera** [comment]
While this is not the recommended way of using anypin, as it is intended to be used as a helping pin to define a single node to be able to operate on multiple datatypes, the way to go for this is to implement a custom pin type and in that definition override the serializatiom method so it's never saved.
 Anyway it might be possible to just disable that pin saving option with something like:

"self.out.disableOptions(PinOptions.Storable)"

**Comment by drtrigon** [comment]
For all running into this problem. **Saving works as long as the node has not been executed yet.** So if you load a file, do some edits and then store BEFORE executing, saving works. This is due to the fact that no output data to serialize is available.

@pedroCabrera : Can you go a bit more into detail on how to implement a custom pin as the docu on such things is not really existing yet?
